const menu= [
  {
    id: 0,
    title: "천원의아침밥",
    category: "천원의아침밥",
    price: 1000,
    img: "/menu_img/item-1.jpg",
  },
  {
    id: 1,
    title: "오늘의메뉴",
    category: "오늘의메뉴",
    price: 6500,
    img: "/menu_img/item-2.jpg",
  },
  {
    id: 2,
    title: "4분돼지김치파스타",
    category: "파스타치오",
    price: 7500,
    img: "/menu_img/item-3.jpg",
  },
  {
    id: 3,
    title: "고기리들기름파스타",
    category: "파스타치오",
    price: 6000,
    img: "/menu_img/item-4.jpg",
  },
  {
    id: 4,
    title: "트러플버섯크림파스타",
    category: "파스타치오",
    price: 6500,
    img: "/menu_img/item-5.jpg",
  },
  {
    id: 5,
    title: "대패삼겹크림파스타",
    category: "파스타치오",
    price: 7500,
    img: "/menu_img/item-6.jpg",

  },
  {
    id: 6,
    title: "매콤로제파스타",
    category: "파스타치오",
    price: 7500,
    img: "/menu_img/item-7.jpg",
  },
  {
    id: 7,
    title: "우삼겹알리오올리오파스타",
    category: "파스타치오",
    price: 7000,
    img: "/menu_img/item-8.jpg",
  },
  {
    id: 8,
    title: "직화불막창토핑추가", 
    category: "파스타치오",
    price: 2900,
    img: "/menu_img/item-9.jpg",
  },
  {
    id: 9,
    title: "직화불쭈꾸미토핑추가",
    category: "파스타치오",
    price: 2900,
    img: "/menu_img/item-10.jpg",
   },

  {
    id: 10,
    title: "치킨마오덮밥",
    category: "니나노덮밥",
    price: 7000,
    img: "/menu_img/item-11.jpg",
   },
  {
    id: 11,
    title: "우동돈까스세트",
    category: "니나노덮밥",
    price: 6200,
    img: "/menu_img/item-12.jpg",
  },
  {
    id: 12,
    title: "제육덮밥",
    category: "니나노덮밥",
    price: 6500,
    img: "/menu_img/item-13.jpg",
   },
  {
    id: 13,
    title: "닭갈비덮밥",
    category: "니나노덮밥",
    price: 7000,
    img: "/menu_img/item-14.jpg",
  },
  {
    id: 14,
    title: "오므라이스",
    category: "니나노덮밥",
    price: 7000,
    img: "/menu_img/item-15.jpg",
  },
  {
    id: 15,
    title: "불닭마오덮밥",
    category: "니나노덮밥",
    price: 6500,
    img: "/menu_img/item-16.jpg",
  },

  {
    id: 16,
    title: "제주흑돼지돈까스",
    category: "일식/양식",
    price: 6000,
    img: "/menu_img/item-17.jpg",
  },
  {
    id: 17,
    title: "탄탄면",
    category: "일식/양식",
    price: 6500,
    img: "/menu_img/item-18.jpg",
  },
  {
    id: 18,
    title: "냉모밀",
    category: "일식/양식",
    price: 6500,
    img: "/menu_img/item-19.jpg",
  },
  {
    id: 19,
    title: "카레밥",
    category: "일식/양식",
    price: 4500,
    img: "/menu_img/item-20.jpg",
  },
  {
    id: 20,
    title: "아메리카노",
    category: "샌드위치카페",
    price: 2000,
    img: "/menu_img/item-21.jpg",
  },
  {
    id: 21,
    title: "카페라떼",
    category: "샌드위치카페",
    price: 2900,
    img: "/menu_img/item-22.jpg",
  },
  {
    id: 22,
    title: "카페모카",
    category: "샌드위치카페",
    price: 3200,
    img: "/menu_img/item-23.jpg",
  },
  {
    id: 23,
    title: "돌체라떼",
    category: "샌드위치카페",
    price: 3200,
    img: "/menu_img/item-24.jpg",
  },
  {
    id: 24,
    title: "복숭아아이스티",
    category: "샌드위치카페",
    price: 2300,
    img: "/menu_img/item-25.jpg",
  },
  {
    id: 25,
    title: "아샷추",
    category: "샌드위치카페",
    price: 2800,
    img: "/menu_img/item-26.jpg",
  },
  {
    id: 26,
    title: "햄치즈토스트",
    category: "토스트",
    price: 3900,
    img: "/menu_img/item-27.jpg",
  },
  {
    id: 27,
    title: "에그토스트",
    category: "토스트",
    price: 3900,
    img: "/menu_img/item-28.jpg",
  },
];

export default menu;